import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>TRO App Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          What matters to you?
        </h1>

        <p className={styles.description}>
          Share your preferences and perspectives regarding our rewards offerings.
          <br/>&#128336; It takes less than 10 minutes
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Begin &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
          Copyright TCS
      </footer>
    </div>
  )
}

export default Home
